export const FETCH_LAUNCHES_SUCCESS = 'FETCH_LAUNCHES_SUCCESS';
export const FETCH_LAUNCHES_FAILURE = 'FETCH_LAUNCHES_FAILURE';
export const TOGGLE_INTERESTED = 'TOGGLE_INTERESTED';
export const SELECT_LAUNCH = 'SELECT_LAUNCH';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
